window.SITE_CONFIG = {
  version: 1,
  profile: {
    name: "Ikemasa",
    label: "デジタル名刺",
    tagline: "AI活用・業務改善・プロダクトづくりの相談相手",
    description: "現場の課題を、小さく試せる形に落とすところから手伝います。",
    body:
      "AIを使った業務改善や、プロダクトづくりの支援をしています。現場の課題を丁寧に聞き、小さく試せる形に落とし込むところから伴走します。話すのが好きで、整理するのも得意です。",
    details: [
      { term: "相談しやすいこと", description: "AI活用の入口、業務改善、MVP、壁打ち" },
      { term: "今日の使い方", description: "話した内容を思い出し、必要なら後からつながる" },
    ],
  },
  eventContext: {
    enabled: true,
    kicker: "今日お会いした方へ",
    upcomingKicker: "今回お会いする方へ",
    title: "今日の文脈",
    upcomingTitle: "今回の文脈",
    eventName: "AIなんでも展示会",
    displayDate: "2026.05.06",
    location: "",
    activeFrom: "2026-05-06",
    activeUntil: "2026-05-06",
    note: "会場でお会いした方向けの短いメモです。",
    topicLabel: "今日話せること",
    upcomingTopicLabel: "今回話せること",
    topics: ["AI導入の最初の一歩", "業務効率化の相談", "プロダクト開発の壁打ち"],
  },
  defaultContext: {
    kicker: "Default",
    title: "普段の相談テーマ",
    summary: "イベントがない日も、こんな相談なら話しやすいです。",
    topicLabel: "相談しやすいこと",
    topics: ["AI活用の入口設計", "業務効率化・自動化", "プロダクトづくり", "壁打ち・整理"],
  },
  topics: [
    {
      title: "AI活用の入口設計",
      description: "何から試すべきか、業務にどう入れるかを一緒に整理します。",
    },
    {
      title: "業務効率化・自動化",
      description: "手作業や属人化している流れを、小さく改善できる形に分解します。",
    },
    {
      title: "プロダクトづくり",
      description: "アイデアを画面、仕様、プロトタイプに落とします。",
    },
    {
      title: "壁打ち・整理",
      description: "まだ曖昧な相談を、次の手に変えるところから手伝います。",
    },
  ],
  contacts: [
    {
      id: "email",
      type: "email",
      icon: "mail",
      label: "メールで連絡する",
      value: "",
      detail: "メールアドレス未設定",
      enabled: false,
      showWhenDisabled: true,
    },
    {
      id: "x",
      type: "url",
      icon: "x",
      label: "Xでつながる",
      value: "https://x.com/ikedamasaki",
      detail: "ゆるく情報交換しましょう",
      enabled: true,
      showWhenDisabled: false,
    },
    {
      id: "instagram",
      type: "url",
      icon: "instagram",
      label: "Instagramを見る",
      value: "https://www.instagram.com/ike_ma_sa/",
      detail: "写真や日々の発信など",
      enabled: true,
      showWhenDisabled: false,
    },
    {
      id: "github",
      type: "url",
      icon: "github",
      label: "GitHubを見る",
      value: "https://github.com/ikedamasaki",
      detail: "公開している制作物など",
      enabled: true,
      showWhenDisabled: false,
    },
  ],
};
