window.SITE_CONFIG = {
  version: 1,
  profile: {
    name: "Ikemasa",
    label: "デジタル名刺",
    tagline: "いけまさ",
    description: "非エンジニアなりに、AIエージェントで身の回りを整えたりしてます",
    body: "",
    details: [
      {
        term: "経歴",
        description: "大阪府出身→同志社大学商学部卒業→大手ECで計画管理・施策運用担当",
      },
      { term: "AI歴", description: "2026/03ごろから開始（Claude Code→codex）" },
      { term: "趣味", description: "ファッション・飲酒・音楽・バスケ・バイブコーディング" },
    ],
  },
  eventContext: {
    enabled: true,
    kicker: "今日お会いした方へ",
    upcomingKicker: "今回お会いする方へ",
    title: "今日の文脈",
    upcomingTitle: "今回の文脈",
    eventName: "AIなんでも展示会",
    displayDate: "2026.05.06",
    location: "",
    activeFrom: "2026-05-06",
    activeUntil: "2026-05-06",
    note: "会場でお会いした方向けの短いメモです。",
    topicLabel: "今日話せること",
    upcomingTopicLabel: "今回話せること",
    topics: ["自己紹介", "NotBadについて", "その他なんでも"],
  },
  defaultContext: {
    kicker: "Default",
    title: "普段の相談テーマ",
    summary: "イベントがない日も、こんな相談なら話しやすいです。",
    topicLabel: "相談しやすいこと",
    topics: ["AI活用の入口設計", "業務効率化・自動化", "プロダクトづくり", "壁打ち・整理"],
  },
  sections: {
    topicsTitle: "最近の個人開発",
    profileTitle: "プロフィール",
    contactTitle: "各種SNS（良かったらぜひフォローしてください！）",
  },
  topics: [
    {
      title: "NotBad（Martinと共同）",
      description: "「AIじゃなくて、友人から紹介してもらった服は嬉しくね？」が発端。",
    },
    {
      title: "Shimatta!!!",
      description: "失敗談を集めるレビューサイト（絶賛揉み中）",
    },
    {
      title: "AI秘書",
      description: "Discordから動くAIエージェントBot（codex）",
    },
  ],
  contacts: [
    {
      id: "email",
      type: "email",
      icon: "mail",
      label: "メールで連絡する",
      value: "ikedamasaki0713@gmail.com",
      detail: "",
      enabled: true,
      showWhenDisabled: true,
    },
    {
      id: "x",
      type: "url",
      icon: "x",
      label: "Xでつながる",
      value: "https://x.com/ikedama___",
      detail: "ゆるく情報交換しましょう",
      enabled: true,
      showWhenDisabled: false,
    },
    {
      id: "instagram",
      type: "url",
      icon: "instagram",
      label: "Instagramを見る",
      value: "https://www.instagram.com/ike_ma_sa/",
      detail: "写真や日々の発信など",
      enabled: true,
      showWhenDisabled: false,
    },
    {
      id: "github",
      type: "url",
      icon: "github",
      label: "GitHubを見る",
      value: "https://github.com/ikedamasaki",
      detail: "公開している制作物など",
      enabled: false,
      showWhenDisabled: false,
    },
  ],
};
